# Change these first
owner: jveyes # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: INNOVA SYSTEMS
    url: https://innovasystems.com.co
  - name: JEMAVI
    url: https://jemavi.co
  - name: VILLAVENECIA
    url: https://villavenecia.tonoip.com
  - name: SALUD SOCIAL
    url: https://saludsocial.tonoip.com
  - name: SALVADOR GAVIOTA
    url: https://salvadorgaviota.tonoip.com
  - name: VPN INNOVA
    check: "tcp-ping"
    url: https://vpn.innovasystems.com.co:943/admin
    port: 943
  - name: GOIP
    url: https://goip.innovasystems.com.co
  - name: SUCCIONAR
    url: https://succionar.co
  - name: URBANA
    url: https://urbanaadministradores.com
  - name: TONOIP
    url: https://tonoip.com
  - name: RESERVAME
    url: https://reservame.click
  - name: DISPAPIRUS
    url: https://dispapirus.com
  - name: DISPAPYRUS
    url: https://dispapyrus.com
  - name: GROWING CLUB
    url: https://growingclub.co
  - name: AEREO CHARTER
    url: https://aerochartercolombia.com
  - name: AQUIUB BEAUTY
    url: https://aquiubbeauty.com
  - name: ANTALIA
    url: https://antaliatienda.com
  - name: ADVANCE PACKS
    url: https://advansepacks.com
  - name: GAFASPORT
    url: https://gafasport.co
  - name: TRAPANNI PIZZA
    url: https://trapanipizzaestofada.com
  - name: BIVPUL
    url: https://bivpul.com
  - name: DIANA PULGARIN
    url: https://dianapulgarin.com
  - name: MATIAS LAWYER
    url: https://matiaslawyer.com
  - name: AWOOKING RECORDS
    url: https://awookingrecords.com
  - name: DIMELO KING
    url: https://dimeloking.com
  - name: HIT MUSIC
    url: https://hitsmusic.com.co
  - name: LA FOCACHERIA
    url: https://lafocacheria.com
  - name: NATYASH
    url: https://natyash.com
  - name: PERFUMERIA GOLDSTONE
    url: https://perfumeriagoldstone.com
  - name: REPUESTOS AFS
    url: https://repuestosafs.com
  - name: SAISAC SAS
    url: https://saisacsas.com
  - name: SAISAC SHOP
    url: https://saisacshop.com
  - name: SHEKINA EXTENSIONS
    url: https://shekinaextensions.com
  - name: SOTTO
    url: https://sotto.com.co
  - name: YERBABUENA
    url: https://yerbabuenacolombia.com

assignees:
  - jveyes
  - ingroger84

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.innovasystems.com.co
  # baseUrl: /upptime
  logoUrl: https://www.innovasystems.com.co/wp-content/uploads/2023/01/innova.svg
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Online Status Innova Systems
  introTitle: "**Upptime** es un monitor de estado en linea para servidores, este es de código abierto, ademas cuenta con su propia página de estado, impulsado completamente por GitHub."
  navbar:
    - title: Online Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  status-website:
    faviconSvg: https://www.innovasystems.com.co/wp-content/uploads/2023/01/innova.svg

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
